/**
 * metadata.ts — Centralized metadata generation for all tool responses.
 *
 * Provides professional-use warnings, data freshness tracking, and source authority disclosure.
 */

import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  /** Data freshness information */
  data_freshness: DataFreshness;

  /** Professional use disclaimer */
  disclaimer: string;

  /** Source authority disclosure */
  source_authority: SourceAuthority;

  /** Known coverage gaps */
  coverage_gaps: string[];

  /** EU AI Act transparency notice */
  ai_disclosure: string;
}

export interface DataFreshness {
  /** Last database update timestamp */
  statute_last_updated: string | null;

  /** Last treaty/regulation sync timestamp */
  treaty_last_sync: string | null;

  /** Warning if data appears stale (>30 days) */
  staleness_warning: string | null;
}

export interface SourceAuthority {
  /** Primary data source description */
  primary_source: string;

  /** Authority level assessment */
  authority_level: 'official' | 'community-maintained';

  /** Verification requirement */
  verification_required: string;
}

/**
 * Generate standard metadata for tool responses.
 *
 * This provides consistent professional-use warnings, data freshness tracking,
 * and source authority disclosure across all tools.
 *
 * @param db - Optional database handle. If not provided, data freshness checks are skipped.
 */
export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  const sourceAuthority = getSourceAuthority();

  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL OR MEDICAL ADVICE. This tool is for research purposes only and does not constitute professional legal, medical, or regulatory advice. Always verify citations with official sources before relying on them in health law, regulatory, or clinical matters. Users are solely responsible for verifying accuracy and currency of all information.',
    source_authority: sourceAuthority,
    coverage_gaps: [
      'National health law implementation',
      'Clinical trial regulations by country',
      'Historical treaty versions',
      'WHO emergency guidance updates'
    ],
    ai_disclosure: 'AI-assisted health law research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use.'
  };
}

/**
 * Return empty data freshness when database is not available.
 */
function getEmptyDataFreshness(): DataFreshness {
  return {
    statute_last_updated: null,
    treaty_last_sync: null,
    staleness_warning: 'Data freshness information unavailable (tool does not query database)'
  };
}

/**
 * Check data freshness and generate staleness warnings.
 */
function getDataFreshness(db: Database): DataFreshness {
  // Check regulation/treaty last_updated
  let statuteLastUpdated: string | null = null;
  try {
    const statuteRow = db.prepare(`
      SELECT MAX(last_updated) as max_date
      FROM legal_documents
      WHERE type IN ('regulation', 'treaty') AND last_updated IS NOT NULL
    `).get() as { max_date: string | null } | undefined;
    statuteLastUpdated = statuteRow?.max_date || null;
  } catch {
    // Ignore errors
  }

  // Check treaty sync metadata
  let treatyLastSync: string | null = null;
  try {
    const syncRow = db.prepare(`
      SELECT last_sync_date
      FROM treaty_sync_metadata
      WHERE id = 1
    `).get() as { last_sync_date: string } | undefined;
    treatyLastSync = syncRow?.last_sync_date || null;
  } catch {
    // Table might not exist yet
  }

  // Calculate staleness warning (30 day threshold)
  const stalenessWarning = calculateStalenessWarning(statuteLastUpdated, treatyLastSync);

  return {
    statute_last_updated: statuteLastUpdated,
    treaty_last_sync: treatyLastSync,
    staleness_warning: stalenessWarning
  };
}

/**
 * Generate staleness warning if data is >30 days old.
 */
function calculateStalenessWarning(
  regulationDate: string | null,
  treatyDate: string | null
): string | null {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const warnings: string[] = [];

  if (regulationDate) {
    const regulationTimestamp = new Date(regulationDate);
    if (regulationTimestamp < thirtyDaysAgo) {
      const daysOld = Math.floor((now.getTime() - regulationTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Health regulation data is ${daysOld} days old - WHO updates may have been published`);
    }
  } else {
    warnings.push('Regulation update timestamp unavailable');
  }

  if (treatyDate) {
    const treatyTimestamp = new Date(treatyDate);
    if (treatyTimestamp < thirtyDaysAgo) {
      const daysOld = Math.floor((now.getTime() - treatyTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Treaty data is ${daysOld} days old - new resolutions or amendments may be missing`);
    }
  }

  return warnings.length > 0 ? warnings.join('. ') : null;
}

/**
 * Get source authority disclosure.
 */
function getSourceAuthority(): SourceAuthority {
  return {
    primary_source: 'WHO (who.int), International Health Regulations, WMA, global health law treaties',
    authority_level: 'official',
    verification_required: 'ALWAYS cross-check with official WHO/treaty publications before relying on output in health law or regulatory work.'
  };
}

/**
 * Wrapper type for tool responses that includes metadata.
 */
export interface ToolResponse<T> {
  /** Tool-specific results */
  results: T;

  /** Professional-use metadata and warnings */
  _metadata: ResponseMetadata;
}
